ResourceManagement/Models/IT/AssetModel.cs
using System;

namespace ResourceManagement.Models.IT
{
    public class AssetModelData
    {
        //
        public string AllocationStatus { get; set; }
        //
        public string Description { get; set; }

        public string AssetType { get; set; }

        public string AssetManufacturer { get; set; }

        //
        public string AssignedAsset { get; set; }

        //Charger Details
        public string ChargerDetails { get; set; }

        public string ChargerCapicity { get; set; }
        public string AssetHostName { get; set; }


        //
        public string MouseDetails { get; set; }
        public string AssetModel { get; set; }

        //
        public string AccessControl { get; set; }

        //Charger Asset ID
        public string ChargerSerialNo { get; set; }

        //
        public string Functionality { get; set; }

        public string USBPortStatus { get; set; }

        //
        public string ExpressCode { get; set; }

        //
        public string Headsets { get; set; }

        //
        public string BarcodeID { get; set; }

        public string ServiceTag { get; set; }

        public string AssetMacNo { get; set; }

        //Asset ID
        public string AssetSerialNo { get; set; }

        //OS Version
        public string OperatingSystemDetail { get; set; }

        public string DisplaySize { get; set; }

        //
        public string IPAddress { get; set; }

        //
        public string WIFIIP { get; set; }

        public DateTime WarrentyStartDate { get; set; }

        public DateTime WarrentyEndDate { get; set; }

        //
        public DateTime PurchaseDate { get; set; }

        //
        public string PurchaseLocation { get; set; }

        public string PurchaseVendor { get; set; }

        public string WarrentyStatus { get; set; }

        //RAM
        public string RAM_Size { get; set; }

        public string ROM_Size { get; set; }

        //
        public string OS { get; set; }

        public string Remarks { get; set; }

        public string CreatedByName { get; set; }
        public string CreatedByID { get; set; }
        public string CreatedByEmail { get; set; }

        public DateTime SoldOutDate { get; set; }

        public int SoldoutPrice { get; set; }

        public string SoldOutStatus { get; set; }

        public string SoldOutVendor { get; set; }


        public JsonResponseModel jsonResponse { get; set; } = new JsonResponseModel();

    }

    public class GetAssetModelByEmp
    {
        //
        public string EmpID { get; set; }
    }

    public class GetAssetModelByAsset
    {
        //
        public string AssetType { get; set; }
    }


    public class GetAssetModel
    {
        public string EmployeeID { get; set; }
        public string FilterBy { get; set; }
        public string AssetType { get; set; }
        public string Category { get; set; }
        public string EmployeeName { get; set; }
        public string AssetID { get; set; }
    }

    public class AssignAssetModel
    {
        public string EmployeeID { get; set; }
        public string AssetType { get; set; }
        public string EmployeeName { get; set; }
        public string EmployeeEmail { get; set; }
        public string AssetID { get; set; }
        public string itadminIds { get; set; }
        public string UploadedByEmpName { get; set; }
        public string UploadedByEmpID { get; set; }
        public string UploadedByEmpEmail { get; set; }
        public string UploadedByMobile { get; set; }
        public string Remarks { get; set; }
        public string AssetTxn { get; set; }

    }

    public class AssetDataPoint
    {
        public string Priority { get; set; }
        public string label { get; set; }
        public double y { get; set; }
        public double totalTickets { get; set; }
    }

    public class VendorModel
    {
        public string VendorName { get; set; }
        public string VendorAddress { get; set; }
        public string VendorCity { get; set; }
        public string VendorEmailAddress { get; set; }
        public string VendorStatus { get; set; }
        public string VendorTxn { get; set; }
        public string VendorRemarks { get; set; }
        public string VendorContactNumber { get; set; }
        public string itadminIds { get; set; }
        public string Action { get; set; }
        public int UniqNo { get; set; }
    }
}

ResourceManagement/Controllers/ITController.cs
using ResourceManagement.Models;
using ResourceManagement.Models.IT;
using System.IO;
using System.Web;
using System.Web.Mvc;
using System.Linq;
using System.Configuration;
using Newtonsoft.Json;
using System.Web.UI;
using System.Collections.Generic;
using iTextSharp.text;
using iTextSharp.text.html.simpleparser;
using iTextSharp.text.pdf;
using System;

using Microsoft.Ajax.Utilities;
using static ResourceManagement.Helpers.EmployeeHelper;
using static ResourceManagement.Helpers.AssetsHelper;
using static ResourceManagement.Helpers.VendorHelper;

namespace ResourceManagement.Controllers
{
    using static Helpers.DateHelper;
    using static Helpers.MediaHelper;
    using static Helpers.MVCExtension;
    using static Helpers.EmailHelper;


    public class ITController : Controller
    {
        // GET: Employee    
        public ActionResult Index()
        {
            return null;
        }

        ////https://www.jqueryscript.net/text/Rich-Text-Editor-jQuery-RichText.html
        public ActionResult ScheduleMaintenance()
        {
            var employeeModel = Session["UserModel"] as RMA_EmployeeModel;

            var ITModel = new ITModel();
            ITModel.RMA_EmployeeModel = employeeModel;

            using (TimeSheetEntities db = new TimeSheetEntities())
            {
                var itAdminEmplist = db.AMBC_Active_Emp_view.Where(a => a.Access_Role.Equals("itadmin") && a.Project_Status == "Active").ToList();
                if (itAdminEmplist != null && itAdminEmplist.Count() > 0)
                {
                    ITModel.ITAdminUsers = itAdminEmplist;
                }
            }

            return View(ITModel);
        }

        public JsonResult GenerateEmailBody(ITScheduleMaintenanceModel maintenanceModel)
        {
            var emailBody = RenderPartialToString(this, "schedulemaintenanceemail", maintenanceModel, ViewData, TempData);
            return Json(emailBody, JsonRequestBehavior.AllowGet);
        }

        public JsonResult ScheduleMaintenanceEmailTrigger(ITScheduleMaintenanceModel maintenanceModel)
        {
            //var emailBody = RenderPartialToString(this, "schedulemaintenanceemail", maintenanceModel, ViewData, TempData);
            maintenanceModel.EmailBody = maintenanceModel.EmailBody.Trim();
            var emailBody = RenderPartialToString(this, "schedulemaintenanceemail", maintenanceModel, ViewData, TempData);

            if (!string.IsNullOrWhiteSpace(maintenanceModel.CC) && !maintenanceModel.CC.Contains(maintenanceModel.UploadedByEmail))
            {
                maintenanceModel.CC += "," + maintenanceModel.UploadedByEmail;
            }
            else
            {
                if (string.IsNullOrWhiteSpace(maintenanceModel.CC))
                {
                    maintenanceModel.CC += maintenanceModel.UploadedByEmail;
                }
            }

            Models.Email.SendEmail emailModel = new Models.Email.SendEmail()
            {
                To = maintenanceModel.TO,
                BCC = maintenanceModel.BCC,
                Subject = maintenanceModel.Subject,
                CC = maintenanceModel.CC,
                EmailBody = emailBody,
                inputObject = maintenanceModel,
                SpecificUserName = ConfigurationManager.AppSettings["ITSMTPUserName"],
                SpecificPassword = ConfigurationManager.AppSettings["ITSMTPPassword"]

            };

            var EmailResponse = SendEmailFromHRMS(emailModel);

            return Json(EmailResponse, JsonRequestBehavior.AllowGet);
        }

        public ActionResult AssetAddUpdate()
        {
            var model = FilDefaultITModel();
            return View(model);
        }

        public ActionResult VendorAddUpdate()
        {
            var model = FilDefaultITModel();
            return View(model);
        }

        public ActionResult ViewVendors()
        {
            var model = FilDefaultITModel();
            return View(model);
        }

        public ActionResult PurchaseRequest()
        {
            var model = FilDefaultITModel();
            return View(model);
        }

        public ActionResult MMReportgenerate()
        {
            ITModel ITModel = FilDefaultITModel();
            return View(ITModel);
        }

        private ITModel FilDefaultITModel()
        {
            var employeeModel = Session["UserModel"] as RMA_EmployeeModel;
            var ITModel = new ITModel();
            ITModel.RMA_EmployeeModel = employeeModel;
            ITModel.MonthsList = MonthList();


            using (TimeSheetEntities db = new TimeSheetEntities())
            {
                var Assets = db.AmbcNewITAssetMgmts.Where(x => x.AssetSerialNo != "").ToList();
                if (Assets != null && Assets.Count() > 0)
                {
                    ITModel.AmbcNewITAssetMgmt = Assets;
                }

                var itAdminEmplist = db.AMBC_Active_Emp_view.Where(a => a.Access_Role.Equals("itadmin") && a.Project_Status == "Active").ToList();
                if (itAdminEmplist != null && itAdminEmplist.Count() > 0)
                {
                    ITModel.ITAdminUsers = itAdminEmplist;
                }

                var locations = db.Locations.ToList();
                if (locations != null && locations.Count() > 0)
                {
                    ITModel.Locations = locations;
                }

                var assetTypes = db.AssetTypes.ToList();
                if (assetTypes != null && assetTypes.Count() > 0)
                {
                    ITModel.AssetTypes = assetTypes;
                }

                var sysRAMs = db.SysRAMDetails.ToList();
                if (sysRAMs != null && sysRAMs.Count() > 0)
                {
                    ITModel.SysRAM = sysRAMs;
                }

                var sysOS = db.SysOSDetails.ToList();
                if (sysOS != null && sysOS.Count() > 0)
                {
                    ITModel.SysOS = sysOS;
                }

                var vendors = db.tbl_Vendor_Detail.Where(x => x.VendorStatus == "Active").ToList();
                if (vendors != null && vendors.Count() > 0)
                {
                    ITModel.Vendors = vendors;
                }
            }

            return ITModel;
        }

        public JsonResult MMReportgenerateAjax(AMBCITMonthlyMaintenance monthlyMaintenanceModel, string itadminIds)
        {
            var inputModel = new ITMaintenanceEmailAck();
            var emailModel = new Models.Email.SendEmail();
            try
            {
                monthlyMaintenanceModel.CreatedDate = System.DateTime.Now;
                using (TimeSheetEntities context = new TimeSheetEntities())
                {

                    context.AMBCITMonthlyMaintenances.Add(monthlyMaintenanceModel);
                    context.SaveChanges();
                    inputModel.SelectedEmp = context.AMBC_Active_Emp_view.Where(x => x.Project_Status == "Active" && x.Employee_ID == monthlyMaintenanceModel.EmployeeID).ToList();

                    inputModel.AMBCITMonthlyMaintenance = monthlyMaintenanceModel;
                    inputModel.ITActivities = JsonConvert.DeserializeObject<List<ITMaintenanceActivityModel>>(monthlyMaintenanceModel.PerformedActivityInfo.ToString());
                    inputModel.itadminIds = itadminIds;
                }

                return ITMaintenaceAckEmailTrigger(inputModel);
            }
            catch (System.Exception ex)
            {
                emailModel.JsonResponse.StatusCode = 500;
                if (ex.InnerException != null && ex.InnerException.InnerException != null && !string.IsNullOrEmpty(ex.InnerException.InnerException.Message))
                {
                    var actuallErrors = ex.InnerException.InnerException.Message.Split('.');
                    foreach (var actuallError in actuallErrors)
                    {
                        if (actuallError.ToLowerInvariant().Contains("duplicate key value is"))
                        {
                            emailModel.JsonResponse.Message = actuallError;
                        }
                    }
                }
                else
                {
                    emailModel.JsonResponse.Message = ex.Message;
                }

                emailModel.inputObject = monthlyMaintenanceModel;
            }
            return Json(JsonConvert.SerializeObject(emailModel), JsonRequestBehavior.AllowGet);
        }

        public JsonResult ITMaintenaceAckEmailTrigger(ITMaintenanceEmailAck ITMaintenanceEmailAck)
        {
            var emailBody = RenderPartialToString(this, "MMAckEmail", ITMaintenanceEmailAck, ViewData, TempData);
            if (!string.IsNullOrWhiteSpace(ITMaintenanceEmailAck.itadminIds) && !ITMaintenanceEmailAck.itadminIds.Contains(ITMaintenanceEmailAck.AMBCITMonthlyMaintenance.UploadedByEmail))
            {
                ITMaintenanceEmailAck.itadminIds += "," + ITMaintenanceEmailAck.AMBCITMonthlyMaintenance.UploadedByEmail;
            }
            else
            {
                if (string.IsNullOrWhiteSpace(ITMaintenanceEmailAck.itadminIds))
                {
                    ITMaintenanceEmailAck.itadminIds += ITMaintenanceEmailAck.AMBCITMonthlyMaintenance.UploadedByEmail;
                }
            }


            Models.Email.SendEmail emailModel = new Models.Email.SendEmail()
            {
                To = ITMaintenanceEmailAck.AMBCITMonthlyMaintenance.Emailaddress,
                Subject = "MM Report - " + ITMaintenanceEmailAck.AMBCITMonthlyMaintenance.MaintenanceMonth.Replace("-", ", ") + " - Asset#: " + ITMaintenanceEmailAck.AMBCITMonthlyMaintenance.AssetID,
                CC = ITMaintenanceEmailAck.itadminIds,
                EmailBody = emailBody,
                inputObject = ITMaintenanceEmailAck,
                SpecificUserName = ConfigurationManager.AppSettings["ITSMTPUserName"],

ResourceManagement/Views/IT/AssetAddUpdate.cshtml
@model ResourceManagement.Models.IT.ITModel

@{
    ViewBag.Title = "Asset Add Update Page";

    var bannerModel = new ResourceManagement.Models.BannerInfo();
    bannerModel.BannerName = "INVENTORY ADD OR UPDATE";
    bannerModel.BannerImagePath = "/Assets/Banner/View Assets.jpg";
}

@Html.Partial("~/Views/Home/_MenuNavigation.cshtml", Model.RMA_EmployeeModel)
@Html.Partial("~/Views/Home/_BannerInfo.cshtml", bannerModel)

@Html.Partial("~/Views/IT/_AssetInfo.cshtml", Model)

<br />

@Html.Partial("~/Views/Home/_ModalAlerts.cshtml")

ResourceManagement/Views/IT/PurchaseRequest.cshtml
@model ResourceManagement.Models.IT.ITModel

@{
    ViewBag.Title = "Purchase request page";

    var bannerModel = new ResourceManagement.Models.BannerInfo();
    bannerModel.BannerName = "PURCHASE REQUEST";
    bannerModel.BannerImagePath = "/Assets/Banner/purchase.jpg";
}

@Html.Partial("~/Views/Home/_MenuNavigation.cshtml", Model.RMA_EmployeeModel)
@Html.Partial("~/Views/Home/_BannerInfo.cshtml", bannerModel)

<div class="card card-body" style="border-radius: 10px">
    <div class="card timesheet-card">
        <div class="card-body ">
            <div class="row">
                <div class="col-md-4">
                    <div class="form-group">
                        <label for="assetassettype">Asset Type<b style="color:red">*</b></label>
                        <select id="assetassettype" name="assetassettype" class="form-control form-select form-select-lg mb-3" required>
                            <option value="" disabled selected>Select Type</option>
                            <option value="Laptop">Laptop</option>
                            <option value="Desktop">Desktop</option>
                            <option value="MacBook">MacBook</option>
                            <option value="MacBook">Tablet</option>
                            <option value="MacBook">Headset</option>
                            <option value="MacBook">Mouse</option>
                            <option value="MacBook">Charger</option>
                            <option value="MacBook">Mobile</option>
                            <option value="MacBook">Other</option>
                        </select>
                    </div>
                </div>

                <div class="col-md-4">
                    <div class="form-group">
                        <label for="vendorlocation">Vendor Location<b style="color:red">*</b></label>
                        <select id="vendorlocation" name="vendorstatus" class="form-control form-select form-select-lg mb-3" required>
                            <option value="" disabled selected>Select Location</option>
                            <option value="Hyderabad">Hyderabad</option>
                            <option value="Madurai">Madurai</option>
                        </select>
                    </div>
                </div>

                <div class="col-md-4">
                    <div class="form-group">
                        <label for="vendorstatus">Vendors<b style="color:red">*</b></label>
                        <select id="vendorstatus" name="vendorstatus" class="form-control form-select form-select-lg mb-3" required>
                            <option value="" disabled selected>Select Vendor</option>
                            <option value="Hyderabad">Vendor1</option>
                            <option value="Madurai">Vendor2</option>
                        </select>
                    </div>
                </div>

                <div class="col-md-8">
                    <div class="form-group">
                        <label for="vendoraddress">Upload quotetion<b style="color:red">*</b></label>
                        <input type="file" name="ExcelFile" id="reportupload" required />
                    </div>
                </div>


                <div class="col-md-12">
                    <div class="form-group">
                        <label for="vendorremarks">Remarks</label>
                        <textarea class="form-control" id="vendorremarks" style="min-width: 100%" placeholder="vendorremarks"></textarea>
                    </div>
                </div>

            </div>

            <br />
            <div class="modal-footer mt-xl-4">
                <button type="submit" class="btn btn-info btn-lg btn-vendor-addupdate" style="width:140px; height:35px; border-radius:10px"><b style="font-size: 16px">Purchase Request</b></button>
            </div>

        </div>
    </div>
</div>


<div>
    @{
        var itEmpEmailIds = "";
    }
    @foreach (var itAdmin in Model.ITAdminUsers)
    {
        itEmpEmailIds += itAdmin.AMBC_Mail_Address.Trim() + ",";
    }

    <div class="it-admin-list" style="display:none">@itEmpEmailIds.Trim(',')</div>
</div>


<br />

@Html.Partial("~/Views/Shared/_EmployeeDetails.cshtml", Model.RMA_EmployeeModel)
@Html.Partial("~/Views/Home/_ModalAlerts.cshtml")

<script>

</script>

ResourceManagement/Views/IT/ViewReport.cshtml
@model ResourceManagement.Models.IT.ITModel

@{
    ViewBag.Title = "Asset Upload Report Page";


    var bannerModel = new ResourceManagement.Models.BannerInfo();
    bannerModel.BannerName = "VIEW IT REPORTS";
    bannerModel.BannerImagePath = "/Assets/Banner/leave-report.png";
}

@Html.Partial("~/Views/Home/_MenuNavigation.cshtml", Model.RMA_EmployeeModel)

@Html.Partial("~/Views/Home/_BannerInfo.cshtml", bannerModel)

<div class="card card-body" style="border-radius: 10px">
    <div class="card upload-it-report-card">
        <div class="card-body ">
            <div class="row">
                <div class="col-md-4">
                    <div class="form-group selectemp-div">
                        <label for="selectEmployeenameandemail">Employee Name<b style="color:red">*</b></label>
                        <select id="selectEmployeenameandemail" name="selectEmployeenameandemail" class="form-control form-select form-select-lg mb-3" style="background-color:white">
                            <option disabled selected value=""> -- Select Employee Name -- </option>
                        </select>
                        <div class="invalid-emp" style="display: none; color: red">
                            Please Select Employee
                        </div>
                    </div>
                </div>

                <div class="col-md-4">
                    <div class="form-group">
                        <label for="assetAssignID">Asset ID<b style="color:red">*</b></label>
                        <select id="assetAssignID" name="assetAssignID" class="form-control form-select form-select-lg mb-3" required>
                            <option value="" disabled selected>Select Asset ID</option>
                            @foreach (var asset in Model.AmbcNewITAssetMgmt)
                            {
                                <option value="@asset.AssetSerialNo">@asset.AssetSerialNo</option>
                            }
                        </select>
                        <div class="invalid-assetid" style="display: none; color: red">
                            Please Select Aseet ID
                        </div>
                    </div>
                </div>

                <div class="col-md-4">
                    <div class="form-group">
                        <label for="assetUploadMonth">Month<b style="color:red">*</b></label>
                        <select id="assetUploadMonth" name="assetUploadMonth" class="form-control form-select form-select-lg mb-3" required>
                            <option value="" disabled selected>Select Month</option>
                            @foreach (var month in Model.MonthsList)
                            {
                                <option value="@month.Value">@month.Text</option>
                            }
                        </select>
                        <div class="invalid-month" style="display: none; color: red">
                            Please Select Month
                        </div>
                    </div>
                </div>
            </div>

            <br />
            <div class="modal-footer mt-xl-4">
                <button type="submit" class="btn btn-info btn-lg btn-view-it-report" style="width:150px; height:35px; border-radius:10px"><b style="font-size: 16px">View Report</b></button>
            </div>
        </div>
    </div>
</div>

<br />
<br />
<div class="card card-body upload-it-report-body" style="border-radius: 10px; display: none">
    <div class="card upload-it-report-card">
        <div class="card-body ">
            @using (Html.BeginForm("DownloadReport", "IT", FormMethod.Post, new { id = "itdownloadform" }))
            {
                <input type="hidden" name="GridHtml" />
                <div id="report-container">
                    <table class="table-leaveinfo" style="margin-top: 4px; width:100%">
                        <thead class="table-bordered" style="height: 35px !important">
                            <tr style="background-color: #005983">
                                @if (Model.RMA_EmployeeModel.AMBC_Active_Emp_view.Access_Role == "administrator")
                                {
                                    <th class="" scope="col" width="30" style="color: white; text-align: center">Action</th>
                                }
                                else
                                {
                                    <th class="" scope="col" width="30" style="color: white; text-align: center; display:none">Action</th>
                                }

                                <th class="" scope="col" width="30" style="color: white; text-align: center">Name</th>
                                <th class="" scope="col" width="30" style="color: white; text-align: center">Asset#</th>
                                <th class="" scope="col" width="30" style="color: white; text-align: center">Month</th>
                                <th class="" scope="col" width="30" style="color: white; text-align: center">Type</th>
                                <th class="" scope="col" width="30" style="color: white; text-align: center">Report</th>
                                <th class="" scope="col" width="30" style="color: white; text-align: center">Date</th>
                                <th class="" scope="col" width="30" style="color: white; text-align: center">Ack</th>
                            </tr>
                        </thead>

                        <tbody class="itreport-table-grid">
                            <tr style="background-color: #ccffcc">
                            </tr>

                        </tbody>
                    </table>
                </div>
            }
        </div>
    </div>
</div>

@Html.Partial("~/Views/Shared/_EmployeeDetails.cshtml")
@Html.Partial("~/Views/Home/_ModalAlerts.cshtml")

<br />
<script>

    jQuery("#selectEmployeenameandemail").change(function (evt) {
        GetAssetsByEmpID(jQuery('#selectEmployeenameandemail :selected').val().split('|')[0]);
    });


    function DownloadITReport(ele) {
        var parentElement = $(ele).parents('.it-report-tr');

        var ITDownloadReportModel = {
            FileName: $(ele).html(),
            ReportMonth: parentElement.find('td.report-month').html(),
            UniqueNumber: $(ele).attr("data-uniqueid"),
            EmpName: parentElement.find('td.report-empname').html(),
            EmpID: parentElement.find('td.report-empname').attr("data-empid"),
            ReportType: parentElement.find('td.report-type').html(),
            AssetID: parentElement.find('td.report-assetid').html(),
        }

        var GridHtml = JSON.stringify(ITDownloadReportModel).toString();
        $("input[name='GridHtml']").val(GridHtml);

        $('form#itdownloadform').submit();
    }

    function DeleteITReport(ele) {
        var parentElement = $(ele).parents('.it-report-tr');
        var ITReportDeleModel = {
            Action: "Delete",
            UniqueNumber: $(ele).attr("data-uniqueid"),
            ReportType: parentElement.find('td.report-type').html(),
            AssetID: parentElement.find('td.report-assetid').html(),
        }
        ViewReport(ITReportDeleModel);
    }


    function ViewReport(model) {
        var isFormValidated = AssetFormValidated();
        if (isFormValidated == false) {
            return;
        }

        jQuery('.upload-it-report-body').show();
        $('.itreport-table-grid').empty();
        var itReportModel = {
            EmployeeID: jQuery('#selectEmployeenameandemail :selected').val().split('|')[0],
            EmployeeName: jQuery('#selectEmployeenameandemail :selected').text(),
            UploadedMonth: jQuery('#assetUploadMonth :selected').val(),
            AssetID: jQuery('#assetAssignID :selected').val(),
            Action: model != undefined ? model.Action : "",
            UniqueNo: model != undefined ? model.UniqueNumber : "",
            ReportType: model != undefined ? model.ReportType : ""
        };

        jQuery.ajax({
            url: "/it/viewitajaxreports",
            type: "POST",
            data: JSON.stringify({ itReportModel: itReportModel }),
            contentType: 'application/json; charset=utf-8',
            success: function (data) {
                var obj = jQuery.parseJSON(data);
                var i = 0;
                jQuery.each(obj, function (i, item) {
                    var backgroundColor = "";

                    if (jQuery('.emprole').val() == "administrator") {
                        $('.itreport-table-grid').append(

                            '<tr style="height: 30px;" class="it-report-tr">'
                            + '<td scope="row" style="padding-left: 25px"><a class="glyphicon glyphicon-remove" href="javascript: void (0);" data-uniqueid="' + item.UniqueNumber + '" onclick=DeleteITReport(this)></a></td>'
                            /*                        + '<td class= "glyphicon glyphicon-download" style = "width: 80px;vertical-align: middle;" > <a href="#" onclick=DownloadIT   Report(this) > ' + item.Remarks + '</a > "</td>'*/
                            + '<td class="report-empname" data-empid="' + item.EmpID + '" style="width: 80px;vertical-align: middle;text-align: center">' + item.EmpName + '</td>'
                            + '<td class="report-assetid" style="width: 80px;vertical-align: middle;text-align: center">' + item.AssetID + '</td>'
                            + '<td class="report-month" style="width: 80px;vertical-align: middle;text-align: center">' + item.ReportMonth + '</td>'
                            + '<td class="report-type" style="width: 80px;vertical-align: middle;text-align: center">' + item.ReportType + '</td>'
                            + '<td class="report-filename" style="width: 80px;vertical-align: middle;text-align: center"><a href="#" data-uniqueid="' + item.UniqueNumber + '" onclick=DownloadITReport(this)>' + item.FileName + '</a></td>'
                            + '<td class="report-type" style="width: 80px;vertical-align: middle;text-align: center">' + item.ReportDate + '</td>'
                            + '<td class="report-type" style="width: 80px;vertical-align: middle;text-align: center">' + item.Ack + '</td>'
                            + '</tr>'
                        )
                    }
                    else {
                        $('.itreport-table-grid').append(

                            '<tr style="height: 30px;" class="it-report-tr">'
                            + '<td scope="row" style="padding-left: 25px; display:none"><a class="glyphicon glyphicon-remove" href="javascript: void (0);"></a></td>'
                            /*                        + '<td class= "glyphicon glyphicon-download" style = "width: 80px;vertical-align: middle;" > <a href="#" onclick=DownloadITReport(this) > ' + item.Remarks + '</a > "</td>'*/
                            + '<td class="report-empname" data-empid="' + item.EmpID + '" style="width: 80px;vertical-align: middle;text-align: center">' + item.EmpName + '</td>'
                            + '<td class="report-assetid" style="width: 80px;vertical-align: middle;text-align: center">' + item.AssetID + '</td>'
                            + '<td class="report-month" style="width: 80px;vertical-align: middle;text-align: center">' + item.ReportMonth + '</td>'
                            + '<td class="report-type" style="width: 80px;vertical-align: middle;text-align: center">' + item.ReportType + '</td>'
                            + '<td class="report-filename" style="width: 80px;vertical-align: middle;text-align: center"><a href="#" data-uniqueid="' + item.UniqueNumber + '" onclick=DownloadITReport(this)>' + item.FileName + '</a></td>'
                            + '<td class="report-type" style="width: 80px;vertical-align: middle;text-align: center">' + item.ReportDate + '</td>'
                            + '<td class="report-type" style="width: 80px;vertical-align: middle;text-align: center">' + item.Ack + '</td>'
                            + '</tr>'
                        )
                    }

                });
            }
        });
    }


    jQuery(".btn-view-it-report").click(function () {
        ViewReport();
    });

</script>